### ISSUE TITLE
IOClient error when using in browser

### ISSUE THREAD

**Issue by Zectbumo** [appsup-dart/firebase#7]
When I try to use Firebase_rest in a Dartium browser I get this error:
Unsupported operation: IOClient isn't supported on this platform.
#0      assertSupported (package:http/src/io.dart:32:3)
#1      Client.Client (package:http/src/client.dart:32:5)
#2      _withClient.<_withClient_async_body> (package:http/http.dart:165:20)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#6      _ScheduleImmediateHelper._handleMutation (dart:html:48762)
#7      MutationObserver._create.<anonymous closure> (dart:html:27252)

Chromium Version 45.0.2454.0 (64-bit)

If I try using dart2js and in Chrome Version 51.0.2704.84 (64-bit) I get this error:

js_helper.dart:1699Uncaught wrapException @ js_helper.dart:1699call$0 @ async_patch.dart:522_microtaskLoop @ schedule_microtask.dart:41dart._startMicrotaskLoop @ schedule_microtask.dart:50call$1 @ async_patch.dart:54call$0 @ js_helper.dart:2375eval$1 @ isolate_helper.dart:462_callInIsolate @ isolate_helper.dart:54invokeClosure @ js_helper.dart:2375(anonymous function) @ js_helper.dart:2395

**Comment by rbellens** [comment]
When using in a browser, you should import 'package:http/browser_client.dart'. See package http(https://pub.dartlang.org/packages/http).

Will update documentation.
